### PR TITLE
Responsive Navigation

### PR DESCRIPTION
**Pull request by adelasofia**
Adds the reference implementation for:

- RH Universal Nav
- RHD Nav
- Topics Nav
- Impl. with all three together
- Logo components (RH and RHD)

Removes two old reference implementations for these same components.

- The expandable search bar is still WIP, and will be coming in a separate PR.

Some screenshots:

image

image

image

image

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@adelasofia This is great! I only noticed a few things, and they are on Firefox

The usernav is not full-width on dropdown:
Screen Shot 2019-10-08 at 1 53 38 PM

Also, when I hover over the Menu sections on the mobile view (Events, Training, Help, Products), I'm seeing two different hover styles. Hovering the `<li>` underlines the text, while hovering the `<a>` (text), underlines and changes the text color to blue.
Screen Shot 2019-10-08 at 1 55 00 PM
Screen Shot 2019-10-08 at 1 55 05 PM

**Comment by adelasofia** [comment]
@mindreeper2420 I pushed the fixes yesterday 👍  I removed the hover styles from the mobile nav, since that's the current implementation we have in prod.

**Comment by mindreeper2420** [comment]
@adelasofia Looks good 👍 . The only thing I noticed, and not sure if this is just a frontend repo thing or will be set in Drupal, is that the Topics navigation doesn't have any horizontal scrolling when I shrink that viewport.

**Comment by mindreeper2420** [comment]
LGTM - nav works as expected.

**Pull request merged**
