### PR TITLE
Feature/cards images aspect #256

### LINKED ISSUE #256: Cards: Don't use min-height on card images to avoid distorting images
Card images have a min-height set, which will distort images if the content creators upload one with an aspect ratio that can't hit that min height. I'd suggest adding a wrapper div around the card element, setting the min-height there and let the card image itself be vertically centered in that space in the event that it's too small for the min-height.

Screenshot from 2019-09-24 08-48-52

### PR DESCRIPTION
**Pull request by alistairmc**
update object cover settings, position center new logotype not cropped

http://redhat.alt-media.dyndns.tv/rhd-frontend/259/components/card-html/

look to bottom to see logo cards
http://redhat.alt-media.dyndns.tv/rhd-frontend/259/components/card-grid/

Fixes #256

### CODE REVIEW

**Comment by alistairmc** [comment]
@sjcox-rh @mindreeper2420 just to confirm you are happy that the card image headers are not all the same size?

**Comment by mindreeper2420** [comment]
@alistairmc They should all be the same size and the spacing should not be that large. It should match what is currently on the demo site and in the Marvel designs.

**Comment by alistairmc** [comment]
@mindreeper2420 but they can't since the source image are all different sizes

**Comment by gdoyle1** [comment]
@alistairmc In addition to the spacing issues that @sjcox-rh and @mindreeper2420 brought up (gap between images and titles)... I have some specifics I'm noticing per content type:

1. Cheat sheet and eBook cards: The spacing between the author name and download CTA should be 16px, it is currently 8px. 
2. Video cards: The play-circle icon in the image isn't appearing, unsure why.
3. Katacoda lesson cards: We don't want that published date there anymore. Should look like this screenshot (in marvel project). There is 16px spacing between the description and download CTA. 
Screen Shot 2019-09-25 at 11 58 15 AM
4. Katacoda course cards: The card and card with flag styles are incorrect... should look like this. 
Screen Shot 2019-09-25 at 12 00 11 PM
5. Product cards: There should be 16px spacing between the description and light CTA. 
6. Series cards: The dividers within the series sidebar card should be extending all the way to where the text begins and ends within the card.

I believe @sjcox-rh that the cards are matching to be the same height within each row because we merged this fix to ensure that cards within one assembly would be the same height (in case the design did not account for that). I don't think that fix will create such drastic differences as it does here though.

**Comment by alistairmc** [comment]
@gdoyle1 @sjcox-rh @mindreeper2420 this issues was to fix the image size, going to move the comments not related to images into other issues.

**Comment by alistairmc** [comment]
@gdoyle1 @sjcox-rh @mindreeper2420 there is a new version pushed

**Comment by gdoyle1** [comment]
@alistairmc This looks good to me! Sorry I didn't realize that this was only about the images also but thanks for moving those comments over to another issue.

**Pull request merged**
