### PR TITLE
Updates Video Hero Speakers

### LINKED ISSUE #271: Multiple authors on Video Hero
**Example of issue:**
- /topics/spring-boot/
- https://developer-preview-3067.ext.us-west.dc.preprod.paas.redhat.com/topics/spring-boot/

**UX Solution:**
Marvel link: https://marvelapp.com/c6c454h/screen/61796034

- [ ] Author tiles need to sit side-by-side with 24px of space in between.
- [ ] Some author titles are long. Ideally, `.rhd-c-author--tile` should have a max-width set so more can fit side-by-side and look uniform. In this scenario, the `.rhd-c-author--tile-title` field would wrap to another line.

### PR DESCRIPTION
**Pull request by adelasofia**
Allows for multiple `Author tiles` (presenters) on the video hero. 

image

Note that the CSS changes on this PR will also update the Curated Events list's authors, but no changes to the Curated Events list are needed on the html side. They styles will take care of it.

(there are HTML changes needed for the Video Hero).

Closes #271

### CODE REVIEW

**Comment by adelasofia** [comment]
@sjcox-rh I've updated the layout to the spacing you requested:

24 px. between each author horizontally, and 16 px. between each row of authors:

image

image

I also updated the Curated Events list (which uses the author tile) to have the same spacing fix:
image

**Comment by sjcox-rh** [comment]
@adelasofia this spacing is much better between the authors, thanks for diving in and changing this last minute! 

I just noticed one tiny thing. What is the spacing between the text and author in the video hero? I only ask because when looking at the curated events list, there seems to be more space and it feels easier to scan through.

Can we possibly match if it's different?

**Comment by adelasofia** [comment]
@sjcox-rh ah! It's 16px on Curated Events, and 8px on the Video Hero. I'm not sure which one is the right one, but it's a quick change if you want me to update either one.

**Comment by sjcox-rh** [comment]
@adelasofia let's update the video hero to 16px to match the list!

**Pull request merged**
