### PR TITLE
Add Video Hero Reference

### PR DESCRIPTION
**Pull request by mindreeper2420**
Add the Video Hero reference to the repo.

Closes https://github.com/redhat-developer/rhd-frontend/issues/95

**Extra Large**
VideoHero_xl

**Large**
VideoHero_lg

**Medium**
VideoHero_md

**Small**
VideoHero_sm

### CODE REVIEW

**Comment by gdoyle1** [comment]
@mindreeper2420 Could we keep the spacing between the video and text to be 24px when it gets to a vertical view (medium and small)?

**Comment by mindreeper2420** [comment]
@gdoyle1 no problem - the following screenshots keep the 24px spacing between the video and title of the text block on medium and small layouts (when stacked vertically).

**Medium**
VideoHero_md

**Small**
VideoHero_sm

**Comment by mindreeper2420** [comment]
@gdoyle1 I just realized that I just put a single video reference - I'll update with a double video reference as well.

**Comment by gdoyle1** [comment]
@mindreeper2420 Perfect! I'll review once you add the double video as well. Thanks!

**Comment by mindreeper2420** [comment]
@gdoyle1 Here are the updated screenshots:

**Large**
VideoHero_double

**Medium**
VideoHero_double-md

**Small**
VideoHero_double-sm

**Comment by gdoyle1** [comment]
Good to go!

**Comment by mindreeper2420** [comment]
@KamiQuasi should be all set now - I merged in the latest changes from master and updated the location of the new `scss` file.

**Pull request merged**
