### PR TITLE
Feature/featured article reference implementation #86

### LINKED ISSUE #86: Featured Article Reference Implementation
This is a grid of cards with a headline. See screenshot below.

Example screenshot:

Screen Shot 2019-09-09 at 1 39 24 PM

### PR DESCRIPTION
**Pull request by alistairmc**
Featured article component center-aligned with 3 cards.

http://redhat.alt-media.dyndns.tv/rhd-frontend/86/components/featured-article/

Fixes #86

### CODE REVIEW

**Comment by alistairmc** [comment]
@gdoyle1 I have updated the h2 size to use the 2xl size (24px)

**Comment by mindreeper2420** [comment]
@sjcox-rh Can you take a look at this PR? Thank you!

**Comment by sjcox-rh** [comment]
@alistairmc just reviewed and it looks good, good to merge from UX end.

**Comment by sjcox-rh** [comment]
@alistairmc @mindreeper2420 OH Adam reminded me in another issue, this needs to be left aligned by default. The preview im seeing now will be how it should render when the centered visual style is applied.

**Comment by sjcox-rh** [comment]
@alistairmc perfect, this is good to go!

**Pull request merged**
