### PR TITLE
CTA form styles #159

### LINKED ISSUE #159: Sign-up Form
- [x] Fields
- [x] CTA
- [x] Text

Style versions

overlabel|Labels in fields
inline|Inline form|Show the form fields inline
sidebar-form|Sidebar form|Show the form as a sidebar
centered|Centered|Center the title and content
use-h1|Use Heading 1|Use H1 markup and styling for the title
background-gray|Gray background|Gray background on the assembly
no-padding-top|No padding top|Remove top padding from this assembly
no-padding-bottom|No padding-bottom|Remove bottom padding from this assembly

### PR DESCRIPTION
**Pull request by alistairmc**
This provides example form styling

http://redhat.alt-media.dyndns.tv/rhd-frontend/159/components/cta_form/

Fixes #159

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
@alistairmc Could we also provide some styles for the base HTML form elements in this issue?

**Comment by alistairmc** [comment]
@jordanpagewhite when you say base do you mean drupal base? if so is there a page where I can grab the html?

**Comment by jordanpagewhite** [comment]
I just mean HTML form element without classes, or at least without the PatternFly classes. Adding a PatternFly class to so many elements for all of the form elements is very tedious, and even then a contrib module _could_ include its own custom template for a form (or form element) that didn't provide the PatternFly classes.

**Comment by alistairmc** [comment]
@jordanpagewhite I have added basic form styles and the eloqua iframe for refrence

**Pull request merged**
